In [1]:
import pandas as pd
import numpy as np

1) The Shape of the Data

In [2]:
#import the courses data
courses = pd.read_csv('../data/raw/courses.csv')

#inspect the df
courses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   course_id      8 non-null      object
 1   department     8 non-null      object
 2   course_number  8 non-null      int64
 3   course_title   8 non-null      object
 4   credits        8 non-null      int64
 5   level          8 non-null      object
 6   delivery       8 non-null      object
dtypes: int64(2), object(5)
memory usage: 580.0+ bytes

The dataframe has 8 observations/rows over 7 variables/columns. It has columns for the Course ID (string), Department (string), Course Number (integer), Course Title (string), the number of credits it's worth (integer), the level of the course (string), and the teaching delivery method (string). There are, fortunately, no missing values. Namely, the course ID or course number will be vital, alongside the number of credits.

Overall, I see few issues occuring with this dataframe. There are no missing values, in addition to clearly defined columns.

In [3]:
#load the enrollments df
enrollments = pd.read_csv('../data/raw/enrollments.csv')

#inspect the df
enrollments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   enrollment_id   59 non-null     object
 1   student_id      59 non-null     object
 2   course_id       59 non-null     object
 3   term            59 non-null     object
 4   status          59 non-null     object
 5   midterm_score   59 non-null     int64
 6   final_score     54 non-null     float64
 7   project_score   56 non-null     float64
 8   attendance_pct  57 non-null     float64
dtypes: float64(3), int64(1), object(5)
memory usage: 4.3+ KB

In [4]:
enrollments.isna().sum()

enrollment_id     0
student_id        0
course_id         0
term              0
status            0
midterm_score     0
final_score       5
project_score     3
attendance_pct    2
dtype: int64

This dataframe has 59 observations across 9 variables. The columns and datatypes are: Enrollemtnt ID (string), Student ID (string), Course ID (string) the term (string), the enrollemnt status (string), the midterm score (integer), the final score (floating point), the project score (floating point), and the attendance percent (floating point). There are a few missing values. The final scores are missing 5 values, the project scores are missing 3 values, and the attendance percent is missing 2 values. I anticipate the Student ID and the Course ID columns to be vital.

The 5 missing final scores are definitely of concern, in addition to the attendance. Those can be vital data points. The term is also a string, which would make it difficult to list them chronologically.

In [5]:
#load the enrollments df
students = pd.read_csv('../data/raw/students.csv')

#inspect the df
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   student_id         30 non-null     object
 1   first_name         30 non-null     object
 2   last_name          30 non-null     object
 3   program            30 non-null     object
 4   year               30 non-null     object
 5   age                28 non-null     float64
 6   active             30 non-null     object
 7   entry_term         30 non-null     object
 8   gpa                27 non-null     float64
 9   credits_completed  30 non-null     int64
 10  advisor            29 non-null     object
dtypes: float64(2), int64(1), object(8)
memory usage: 2.7+ KB

In [6]:
students.isna().sum()

student_id           0
first_name           0
last_name            0
program              0
year                 0
age                  2
active               0
entry_term           0
gpa                  3
credits_completed    0
advisor              1
dtype: int64

The students dataframe has 30 rows across 11 columns. The columns are: Student ID (string), First Name (string), Last Name (string), Program (string), year (string), age (floating point), active status (string), entry term (string), GPA (floating point), credits copleted (integer), and advisor (string). There are a few missing values, including 2 ages, 3 GPAs, and 1 advisor. I expect Student ID to be the key row. 

The year being a string is of concern, since it could be formatted as an integer. The missing values are of little concern, however, since they are extranuous details and not vital.

2) Filtering and Derived Variables

In [7]:
#create a subset
subset = students[
    (students["active"] == "Yes") &
    (students["program"] == "Statistics")
]

subset

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor
5,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45,Dr. Moreno
10,S1011,Isabella,Lopez,Statistics,2nd,18.0,Yes,Fall 2024,3.22,54,Dr. Reed
14,S1015,Mia,Thomas,Statistics,3rd,23.0,Yes,Fall 2024,3.81,36,Dr. Shah
21,S1022,Julian,Wright,Statistics,3rd,19.0,Yes,Spring 2025,NaN,18,Dr. Shah
25,S1026,Isaac,Adams,Statistics,4th,23.0,Yes,Fall 2024,3.29,36,NaN

I subsetted the students into active students in a statistics program.

In [8]:
# Create a derived variable
students["full_name"] = students["first_name"] + " " + students["last_name"]

students.head()

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor,full_name
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno,Avery Nguyen
1,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108,Dr. Shah,Maya Patel
2,S1003,Noah,Garcia,Mathematics,1st,18.0,Yes,Spring 2024,2.81,18,Dr. Reed,Noah Garcia
3,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63,Dr. Kim,Sofia Johnson
4,S1005,Ethan,Kim,Computer Science,4th,19.0,Yes,Spring 2025,NaN,18,Dr. Kim,Ethan Kim

I created a derived column from the first and last name to form a full name.

In [9]:
students.loc[
    students["active"] == "Yes",
    ["full_name", "program", "gpa"]
].head()

       full_name           program   gpa
0   Avery Nguyen       Mathematics  3.51
1     Maya Patel  Computer Science  2.71
2    Noah Garcia       Mathematics  2.81
3  Sofia Johnson  Computer Science  3.05
4      Ethan Kim  Computer Science   NaN

I used head to truncate the output, but this command selects the full name, program, and GPA for active students.

In [10]:
student_ids = [
    ident for ident in students["student_id"]
]

student_ids[0:5]

['S1001', 'S1002', 'S1003', 'S1004', 'S1005']

(Selecting the first 5 of them) I created a list of the Student IDs within the dataset.

3) Joining Tables
The first two tables I will join are the enrollments and the students. This makes the most sense to me, since I will only be adding the information from the students to each enrollment. I will join based on Student ID from both tables.

In [13]:
# merge the tables based on the id, expecting a one-to-one relationship
enrollDetail = enrollments.merge(
    students,
    on = "student_id",
    how = "outer",
    validate="many_to_one"
)
enrollDetail.head()

,enrollment_id,student_id,course_id,term,status,midterm_score,final_score,project_score,attendance_pct,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor,full_name
0,E5001,S1001,C102,Spring 2026,Completed,96.0,65.0,65.0,94.7,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,Dr. Moreno,Avery Nguyen
1,E5002,S1001,C106,Spring 2026,Completed,81.0,80.0,63.0,96.6,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,Dr. Moreno,Avery Nguyen
2,E5003,S1001,C103,Spring 2026,Completed,77.0,67.0,72.0,88.6,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72.0,Dr. Moreno,Avery Nguyen
3,E5004,S1002,C106,Fall 2025,Completed,86.0,NaN,85.0,77.3,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108.0,Dr. Shah,Maya Patel
4,E5005,S1002,C101,Fall 2025,Completed,90.0,55.0,79.0,85.8,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108.0,Dr. Shah,Maya Patel

The resulting dataset adds the student details to the enrollment. Upon inspection, there is one row more than in the original enrollments dataset. One of the students have no enrollments, and I chose an outer join, meaning all keys in both datasets are present, even if they aren't present in the other. This is also mirrored, since there is also an enrollment that presents a student ID not present in the students data.

I validated with a many to one relationship, since students can enroll in several courses, but each enrollment can only have one student. This presented no issues. From here, we can now join the courses table.

In [47]:
studentClassDetail = enrollDetail.merge(
    courses,
    on = "course_id",
    how = "outer",
    validate="many_to_many",
    indicator=True
)

studentClassDetail.head()

,enrollment_id,student_id,course_id,term,status,midterm_score,final_score,project_score,attendance_pct,first_name,...,credits_completed,advisor,full_name,department,course_number,course_title,credits,level,delivery,_merge
0,E5005,S1002,C101,Fall 2025,Completed,90.0,55.0,79.0,85.8,Maya,...,108.0,Dr. Shah,Maya Patel,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
1,E5008,S1004,C101,Fall 2025,Completed,87.0,58.0,NaN,75.6,Sofia,...,63.0,Dr. Kim,Sofia Johnson,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
2,E5010,S1005,C101,Spring 2026,Completed,73.0,57.0,99.0,82.9,Ethan,...,18.0,Dr. Kim,Ethan Kim,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
3,E5013,S1006,C101,Fall 2026,Enrolled,98.0,81.0,82.0,80.0,Liam,...,45.0,Dr. Moreno,Liam Martinez,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both
4,E5018,S1008,C101,Spring 2026,Completed,74.0,70.0,62.0,87.4,Lucas,...,45.0,Dr. Shah,Lucas Wilson,STA,141.0,Exploratory Data Analysis,3.0,Undergraduate,In Person,both

Once again, I validated a many-to-many relationship, since students can have multiple courses, and courses can have multiple students. The indicator shows that most rows came from both data sets, meaning most have matches, but two rows contain a course that does not have information from the courses dataset.No new or duplicate rows were created during this merge, which indicates that there are no courses in the courses dataset that have 0 enrollments.

4) Missing Data and Reshaping

In [48]:
studentClassDetail.isna().sum()

enrollment_id        1
student_id           0
course_id            1
term                 1
status               1
midterm_score        1
final_score          6
project_score        4
attendance_pct       3
first_name           1
last_name            1
program              1
year                 1
age                  5
active               1
entry_term           1
gpa                  6
credits_completed    1
advisor              2
full_name            1
department           2
course_number        2
course_title         2
credits              2
level                2
delivery             2
_merge               0
dtype: int64

We are missing several values within the data. No student IDs are missing, but one of both enrollment IDs and course IDs are missing. One is missing of term, status, and midterm score as well. The most missing is the final score, with 6 missing values, and the project score is missing 4 as well. We have one student ID missing all of the student data, with 5 total ages missing from the student. 6 GPAs are still missing, with 2 advisors missing in addition. There are two rows missing the course information, inclusing the number, title, credits, level, and delivery.

In [49]:
studentClassDetail.isna().mean() * 100

enrollment_id         1.666667
student_id            0.000000
course_id             1.666667
term                  1.666667
status                1.666667
midterm_score         1.666667
final_score          10.000000
project_score         6.666667
attendance_pct        5.000000
first_name            1.666667
last_name             1.666667
program               1.666667
year                  1.666667
age                   8.333333
active                1.666667
entry_term            1.666667
gpa                  10.000000
credits_completed     1.666667
advisor               3.333333
full_name             1.666667
department            3.333333
course_number         3.333333
course_title          3.333333
credits               3.333333
level                 3.333333
delivery              3.333333
_merge                0.000000
dtype: float64

For the percentages, most hang around the 3-5% mark at most, with age, final score, and GPA missing 8-10% of the column information.

In [58]:
studentClassDetail.loc[studentClassDetail["course_id"].isna()]

,enrollment_id,student_id,course_id,term,status,midterm_score,final_score,project_score,attendance_pct,first_name,...,credits_completed,advisor,full_name,department,course_number,course_title,credits,level,delivery,_merge
59,NaN,S1030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Miles,...,36.0,Dr. Kim,Miles Mitchell,NaN,NaN,NaN,NaN,NaN,NaN,left_only

Above shows a student missing an enrollment and course ID. This shows the information for the student, but no other information about their courses.

In [ ]:
#reshape the data
scores_long = studentClassDetail.melt(
    id_vars=["enrollment_id", "student_id", "course_id"],
    value_vars=["midterm_score", "final_score", "project_score"],
    var_name="assessment",
    value_name="score"
)

scores_long.sample(n=7)

    enrollment_id student_id course_id     assessment  score
30          E5056      S1029      C104  midterm_score   88.0
41          E5048      S1024      C106  midterm_score   77.0
16          E5041      S1020      C102  midterm_score   67.0
101         E5048      S1024      C106    final_score   85.0
137         E5045      S1022      C102  project_score   71.0
107         E5044      S1022      C107    final_score   74.0
128         E5049      S1024      C101  project_score   82.0

I took a random sample of the data to show the change. I changed the midterm_score, final_score, and project_score into one "assessment" column which shows which of the 3 is being described. The enrollment ID, student ID, and course ID are kept to make sense of the assessments.

Replacing all missing values with zeros would have drastic consequences. Many of the IDs are strings and non-numeric. Most importantly, for the scores missing, a zero would indicate a failure of completion instead of a true missing value. This would not accurately reflect the student's performance.

In [65]:
#save the data
studentClassDetail.to_csv("../data/processed/studentClassEnrollmentDetail.csv")